
package net.taxcloud;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2015-01-17T13:56:40.875-05:00
 * Generated source version: 2.6.6
 * 
 */
public final class TaxCloudSoap_TaxCloudSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://taxcloud.net", "TaxCloud");

    private TaxCloudSoap_TaxCloudSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TaxCloud.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TaxCloud ss = new TaxCloud(wsdlURL, SERVICE_NAME);
        TaxCloudSoap port = ss.getTaxCloudSoap();  
        
        {
        System.out.println("Invoking getTICsByGroup...");
        java.lang.String _getTICsByGroup_apiLoginID = "";
        java.lang.String _getTICsByGroup_apiKey = "";
        int _getTICsByGroup_ticGroup = 0;
        net.taxcloud.GetTICsRsp _getTICsByGroup__return = port.getTICsByGroup(_getTICsByGroup_apiLoginID, _getTICsByGroup_apiKey, _getTICsByGroup_ticGroup);
        System.out.println("getTICsByGroup.result=" + _getTICsByGroup__return);


        }
        {
        System.out.println("Invoking captured...");
        java.lang.String _captured_apiLoginID = "";
        java.lang.String _captured_apiKey = "";
        java.lang.String _captured_orderID = "";
        net.taxcloud.CapturedRsp _captured__return = port.captured(_captured_apiLoginID, _captured_apiKey, _captured_orderID);
        System.out.println("captured.result=" + _captured__return);


        }
        {
        System.out.println("Invoking deleteExemptCertificate...");
        java.lang.String _deleteExemptCertificate_apiLoginID = "";
        java.lang.String _deleteExemptCertificate_apiKey = "";
        java.lang.String _deleteExemptCertificate_certificateID = "";
        net.taxcloud.DeleteCertificateRsp _deleteExemptCertificate__return = port.deleteExemptCertificate(_deleteExemptCertificate_apiLoginID, _deleteExemptCertificate_apiKey, _deleteExemptCertificate_certificateID);
        System.out.println("deleteExemptCertificate.result=" + _deleteExemptCertificate__return);


        }
        {
        System.out.println("Invoking lookup...");
        java.lang.String _lookup_apiLoginID = "";
        java.lang.String _lookup_apiKey = "";
        java.lang.String _lookup_customerID = "";
        java.lang.String _lookup_cartID = "";
        net.taxcloud.ArrayOfCartItem _lookup_cartItems = null;
        net.taxcloud.Address _lookup_origin = null;
        net.taxcloud.Address _lookup_destination = null;
        boolean _lookup_deliveredBySeller = false;
        net.taxcloud.ExemptionCertificate _lookup_exemptCert = null;
        net.taxcloud.LookupRsp _lookup__return = port.lookup(_lookup_apiLoginID, _lookup_apiKey, _lookup_customerID, _lookup_cartID, _lookup_cartItems, _lookup_origin, _lookup_destination, _lookup_deliveredBySeller, _lookup_exemptCert);
        System.out.println("lookup.result=" + _lookup__return);


        }
        {
        System.out.println("Invoking addTransactions...");
        java.lang.String _addTransactions_apiLoginID = "";
        java.lang.String _addTransactions_apiKey = "";
        net.taxcloud.ArrayOfTransaction _addTransactions_transactions = null;
        net.taxcloud.AddTransactionsRsp _addTransactions__return = port.addTransactions(_addTransactions_apiLoginID, _addTransactions_apiKey, _addTransactions_transactions);
        System.out.println("addTransactions.result=" + _addTransactions__return);


        }
        {
        System.out.println("Invoking getTICGroups...");
        java.lang.String _getTICGroups_apiLoginID = "";
        java.lang.String _getTICGroups_apiKey = "";
        net.taxcloud.GetTICGroupsRsp _getTICGroups__return = port.getTICGroups(_getTICGroups_apiLoginID, _getTICGroups_apiKey);
        System.out.println("getTICGroups.result=" + _getTICGroups__return);


        }
        {
        System.out.println("Invoking ping...");
        java.lang.String _ping_apiLoginID = "";
        java.lang.String _ping_apiKey = "";
        net.taxcloud.PingRsp _ping__return = port.ping(_ping_apiLoginID, _ping_apiKey);
        System.out.println("ping.result=" + _ping__return);


        }
        {
        System.out.println("Invoking addExemptCertificate...");
        java.lang.String _addExemptCertificate_apiLoginID = "";
        java.lang.String _addExemptCertificate_apiKey = "";
        java.lang.String _addExemptCertificate_customerID = "";
        net.taxcloud.ExemptionCertificate _addExemptCertificate_exemptCert = null;
        net.taxcloud.AddCertificateRsp _addExemptCertificate__return = port.addExemptCertificate(_addExemptCertificate_apiLoginID, _addExemptCertificate_apiKey, _addExemptCertificate_customerID, _addExemptCertificate_exemptCert);
        System.out.println("addExemptCertificate.result=" + _addExemptCertificate__return);


        }
        {
        System.out.println("Invoking getExemptCertificates...");
        java.lang.String _getExemptCertificates_apiLoginID = "";
        java.lang.String _getExemptCertificates_apiKey = "";
        java.lang.String _getExemptCertificates_customerID = "";
        net.taxcloud.GetCertificatesRsp _getExemptCertificates__return = port.getExemptCertificates(_getExemptCertificates_apiLoginID, _getExemptCertificates_apiKey, _getExemptCertificates_customerID);
        System.out.println("getExemptCertificates.result=" + _getExemptCertificates__return);


        }
        {
        System.out.println("Invoking verifyAddress...");
        java.lang.String _verifyAddress_uspsUserID = "";
        java.lang.String _verifyAddress_address1 = "";
        java.lang.String _verifyAddress_address2 = "";
        java.lang.String _verifyAddress_city = "";
        java.lang.String _verifyAddress_state = "";
        java.lang.String _verifyAddress_zip5 = "";
        java.lang.String _verifyAddress_zip4 = "";
        net.taxcloud.VerifiedAddress _verifyAddress__return = port.verifyAddress(_verifyAddress_uspsUserID, _verifyAddress_address1, _verifyAddress_address2, _verifyAddress_city, _verifyAddress_state, _verifyAddress_zip5, _verifyAddress_zip4);
        System.out.println("verifyAddress.result=" + _verifyAddress__return);


        }
        {
        System.out.println("Invoking lookupForDate...");
        java.lang.String _lookupForDate_apiLoginID = "";
        java.lang.String _lookupForDate_apiKey = "";
        java.lang.String _lookupForDate_customerID = "";
        java.lang.String _lookupForDate_cartID = "";
        net.taxcloud.ArrayOfCartItem _lookupForDate_cartItems = null;
        net.taxcloud.Address _lookupForDate_origin = null;
        net.taxcloud.Address _lookupForDate_destination = null;
        boolean _lookupForDate_deliveredBySeller = false;
        net.taxcloud.ExemptionCertificate _lookupForDate_exemptCert = null;
        javax.xml.datatype.XMLGregorianCalendar _lookupForDate_useDate = null;
        net.taxcloud.LookupRsp _lookupForDate__return = port.lookupForDate(_lookupForDate_apiLoginID, _lookupForDate_apiKey, _lookupForDate_customerID, _lookupForDate_cartID, _lookupForDate_cartItems, _lookupForDate_origin, _lookupForDate_destination, _lookupForDate_deliveredBySeller, _lookupForDate_exemptCert, _lookupForDate_useDate);
        System.out.println("lookupForDate.result=" + _lookupForDate__return);


        }
        {
        System.out.println("Invoking getTICs...");
        java.lang.String _getTICs_apiLoginID = "";
        java.lang.String _getTICs_apiKey = "";
        net.taxcloud.GetTICsRsp _getTICs__return = port.getTICs(_getTICs_apiLoginID, _getTICs_apiKey);
        System.out.println("getTICs.result=" + _getTICs__return);


        }
        {
        System.out.println("Invoking authorized...");
        java.lang.String _authorized_apiLoginID = "";
        java.lang.String _authorized_apiKey = "";
        java.lang.String _authorized_customerID = "";
        java.lang.String _authorized_cartID = "";
        java.lang.String _authorized_orderID = "";
        javax.xml.datatype.XMLGregorianCalendar _authorized_dateAuthorized = null;
        net.taxcloud.AuthorizedRsp _authorized__return = port.authorized(_authorized_apiLoginID, _authorized_apiKey, _authorized_customerID, _authorized_cartID, _authorized_orderID, _authorized_dateAuthorized);
        System.out.println("authorized.result=" + _authorized__return);


        }
        {
        System.out.println("Invoking returned...");
        java.lang.String _returned_apiLoginID = "";
        java.lang.String _returned_apiKey = "";
        java.lang.String _returned_orderID = "";
        net.taxcloud.ArrayOfCartItem _returned_cartItems = null;
        javax.xml.datatype.XMLGregorianCalendar _returned_returnedDate = null;
        net.taxcloud.ReturnedRsp _returned__return = port.returned(_returned_apiLoginID, _returned_apiKey, _returned_orderID, _returned_cartItems, _returned_returnedDate);
        System.out.println("returned.result=" + _returned__return);


        }
        {
        System.out.println("Invoking authorizedWithCapture...");
        java.lang.String _authorizedWithCapture_apiLoginID = "";
        java.lang.String _authorizedWithCapture_apiKey = "";
        java.lang.String _authorizedWithCapture_customerID = "";
        java.lang.String _authorizedWithCapture_cartID = "";
        java.lang.String _authorizedWithCapture_orderID = "";
        javax.xml.datatype.XMLGregorianCalendar _authorizedWithCapture_dateAuthorized = null;
        javax.xml.datatype.XMLGregorianCalendar _authorizedWithCapture_dateCaptured = null;
        net.taxcloud.AuthorizedRsp _authorizedWithCapture__return = port.authorizedWithCapture(_authorizedWithCapture_apiLoginID, _authorizedWithCapture_apiKey, _authorizedWithCapture_customerID, _authorizedWithCapture_cartID, _authorizedWithCapture_orderID, _authorizedWithCapture_dateAuthorized, _authorizedWithCapture_dateCaptured);
        System.out.println("authorizedWithCapture.result=" + _authorizedWithCapture__return);


        }

        System.exit(0);
    }

}
