
package net.taxcloud;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2015-01-17T13:56:40.821-05:00
 * Generated source version: 2.6.6
 * 
 */
public final class TaxCloudHttpPost_TaxCloudHttpPost_Client {

    private static final QName SERVICE_NAME = new QName("http://taxcloud.net", "TaxCloud");

    private TaxCloudHttpPost_TaxCloudHttpPost_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TaxCloud.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TaxCloud ss = new TaxCloud(wsdlURL, SERVICE_NAME);
        TaxCloudHttpPost port = ss.getTaxCloudHttpPost();  
        
        {
        System.out.println("Invoking verifyAddress...");
        java.lang.String _verifyAddress_uspsUserID = "";
        java.lang.String _verifyAddress_address1 = "";
        java.lang.String _verifyAddress_address2 = "";
        java.lang.String _verifyAddress_city = "";
        java.lang.String _verifyAddress_state = "";
        java.lang.String _verifyAddress_zip5 = "";
        java.lang.String _verifyAddress_zip4 = "";
        net.taxcloud.VerifiedAddress _verifyAddress__return = port.verifyAddress(_verifyAddress_uspsUserID, _verifyAddress_address1, _verifyAddress_address2, _verifyAddress_city, _verifyAddress_state, _verifyAddress_zip5, _verifyAddress_zip4);
        System.out.println("verifyAddress.result=" + _verifyAddress__return);


        }
        {
        System.out.println("Invoking getTICsByGroup...");
        java.lang.String _getTICsByGroup_apiLoginID = "";
        java.lang.String _getTICsByGroup_apiKey = "";
        java.lang.String _getTICsByGroup_ticGroup = "";
        net.taxcloud.GetTICsRsp _getTICsByGroup__return = port.getTICsByGroup(_getTICsByGroup_apiLoginID, _getTICsByGroup_apiKey, _getTICsByGroup_ticGroup);
        System.out.println("getTICsByGroup.result=" + _getTICsByGroup__return);


        }
        {
        System.out.println("Invoking captured...");
        java.lang.String _captured_apiLoginID = "";
        java.lang.String _captured_apiKey = "";
        java.lang.String _captured_orderID = "";
        net.taxcloud.CapturedRsp _captured__return = port.captured(_captured_apiLoginID, _captured_apiKey, _captured_orderID);
        System.out.println("captured.result=" + _captured__return);


        }
        {
        System.out.println("Invoking deleteExemptCertificate...");
        java.lang.String _deleteExemptCertificate_apiLoginID = "";
        java.lang.String _deleteExemptCertificate_apiKey = "";
        java.lang.String _deleteExemptCertificate_certificateID = "";
        net.taxcloud.DeleteCertificateRsp _deleteExemptCertificate__return = port.deleteExemptCertificate(_deleteExemptCertificate_apiLoginID, _deleteExemptCertificate_apiKey, _deleteExemptCertificate_certificateID);
        System.out.println("deleteExemptCertificate.result=" + _deleteExemptCertificate__return);


        }
        {
        System.out.println("Invoking getTICGroups...");
        java.lang.String _getTICGroups_apiLoginID = "";
        java.lang.String _getTICGroups_apiKey = "";
        net.taxcloud.GetTICGroupsRsp _getTICGroups__return = port.getTICGroups(_getTICGroups_apiLoginID, _getTICGroups_apiKey);
        System.out.println("getTICGroups.result=" + _getTICGroups__return);


        }
        {
        System.out.println("Invoking ping...");
        java.lang.String _ping_apiLoginID = "";
        java.lang.String _ping_apiKey = "";
        net.taxcloud.PingRsp _ping__return = port.ping(_ping_apiLoginID, _ping_apiKey);
        System.out.println("ping.result=" + _ping__return);


        }
        {
        System.out.println("Invoking getTICs...");
        java.lang.String _getTICs_apiLoginID = "";
        java.lang.String _getTICs_apiKey = "";
        net.taxcloud.GetTICsRsp _getTICs__return = port.getTICs(_getTICs_apiLoginID, _getTICs_apiKey);
        System.out.println("getTICs.result=" + _getTICs__return);


        }
        {
        System.out.println("Invoking authorized...");
        java.lang.String _authorized_apiLoginID = "";
        java.lang.String _authorized_apiKey = "";
        java.lang.String _authorized_customerID = "";
        java.lang.String _authorized_cartID = "";
        java.lang.String _authorized_orderID = "";
        java.lang.String _authorized_dateAuthorized = "";
        net.taxcloud.AuthorizedRsp _authorized__return = port.authorized(_authorized_apiLoginID, _authorized_apiKey, _authorized_customerID, _authorized_cartID, _authorized_orderID, _authorized_dateAuthorized);
        System.out.println("authorized.result=" + _authorized__return);


        }
        {
        System.out.println("Invoking getExemptCertificates...");
        java.lang.String _getExemptCertificates_apiLoginID = "";
        java.lang.String _getExemptCertificates_apiKey = "";
        java.lang.String _getExemptCertificates_customerID = "";
        net.taxcloud.GetCertificatesRsp _getExemptCertificates__return = port.getExemptCertificates(_getExemptCertificates_apiLoginID, _getExemptCertificates_apiKey, _getExemptCertificates_customerID);
        System.out.println("getExemptCertificates.result=" + _getExemptCertificates__return);


        }
        {
        System.out.println("Invoking authorizedWithCapture...");
        java.lang.String _authorizedWithCapture_apiLoginID = "";
        java.lang.String _authorizedWithCapture_apiKey = "";
        java.lang.String _authorizedWithCapture_customerID = "";
        java.lang.String _authorizedWithCapture_cartID = "";
        java.lang.String _authorizedWithCapture_orderID = "";
        java.lang.String _authorizedWithCapture_dateAuthorized = "";
        java.lang.String _authorizedWithCapture_dateCaptured = "";
        net.taxcloud.AuthorizedRsp _authorizedWithCapture__return = port.authorizedWithCapture(_authorizedWithCapture_apiLoginID, _authorizedWithCapture_apiKey, _authorizedWithCapture_customerID, _authorizedWithCapture_cartID, _authorizedWithCapture_orderID, _authorizedWithCapture_dateAuthorized, _authorizedWithCapture_dateCaptured);
        System.out.println("authorizedWithCapture.result=" + _authorizedWithCapture__return);


        }

        System.exit(0);
    }

}
