package net.taxcloud;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * TaxCloud Web Service
 *
 * This class was generated by Apache CXF 2.6.6
 * 2015-01-17T13:56:41.244-05:00
 * Generated source version: 2.6.6
 * 
 */
@WebServiceClient(name = "TaxCloud", 
                  wsdlLocation = "https://api.taxcloud.net/1.0/TaxCloud.asmx?wsdl",
                  targetNamespace = "http://taxcloud.net") 
public class TaxCloud extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://taxcloud.net", "TaxCloud");
    public final static QName TaxCloudHttpPost = new QName("http://taxcloud.net", "TaxCloudHttpPost");
    public final static QName TaxCloudSoap12 = new QName("http://taxcloud.net", "TaxCloudSoap12");
    public final static QName TaxCloudSoap = new QName("http://taxcloud.net", "TaxCloudSoap");
    static {
        URL url = null;
        try {
            url = new URL("https://api.taxcloud.net/1.0/TaxCloud.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TaxCloud.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://api.taxcloud.net/1.0/TaxCloud.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TaxCloud(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TaxCloud(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaxCloud() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TaxCloud(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TaxCloud(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TaxCloud(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TaxCloudHttpPost
     */
    @WebEndpoint(name = "TaxCloudHttpPost")
    public TaxCloudHttpPost getTaxCloudHttpPost() {
        return super.getPort(TaxCloudHttpPost, TaxCloudHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaxCloudHttpPost
     */
    @WebEndpoint(name = "TaxCloudHttpPost")
    public TaxCloudHttpPost getTaxCloudHttpPost(WebServiceFeature... features) {
        return super.getPort(TaxCloudHttpPost, TaxCloudHttpPost.class, features);
    }
    /**
     *
     * @return
     *     returns TaxCloudSoap
     */
    @WebEndpoint(name = "TaxCloudSoap12")
    public TaxCloudSoap getTaxCloudSoap12() {
        return super.getPort(TaxCloudSoap12, TaxCloudSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaxCloudSoap
     */
    @WebEndpoint(name = "TaxCloudSoap12")
    public TaxCloudSoap getTaxCloudSoap12(WebServiceFeature... features) {
        return super.getPort(TaxCloudSoap12, TaxCloudSoap.class, features);
    }
    /**
     *
     * @return
     *     returns TaxCloudSoap
     */
    @WebEndpoint(name = "TaxCloudSoap")
    public TaxCloudSoap getTaxCloudSoap() {
        return super.getPort(TaxCloudSoap, TaxCloudSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaxCloudSoap
     */
    @WebEndpoint(name = "TaxCloudSoap")
    public TaxCloudSoap getTaxCloudSoap(WebServiceFeature... features) {
        return super.getPort(TaxCloudSoap, TaxCloudSoap.class, features);
    }

}
