package net.taxcloud;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2015-01-17T13:56:40.905-05:00
 * Generated source version: 2.6.6
 * 
 */
@WebService(targetNamespace = "http://taxcloud.net", name = "TaxCloudHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TaxCloudHttpPost {

    @WebMethod(operationName = "VerifyAddress")
    @WebResult(name = "VerifiedAddress", targetNamespace = "http://taxcloud.net", partName = "Body")
    public VerifiedAddress verifyAddress(
        @WebParam(partName = "uspsUserID", name = "uspsUserID", targetNamespace = "http://taxcloud.net")
        java.lang.String uspsUserID,
        @WebParam(partName = "address1", name = "address1", targetNamespace = "http://taxcloud.net")
        java.lang.String address1,
        @WebParam(partName = "address2", name = "address2", targetNamespace = "http://taxcloud.net")
        java.lang.String address2,
        @WebParam(partName = "city", name = "city", targetNamespace = "http://taxcloud.net")
        java.lang.String city,
        @WebParam(partName = "state", name = "state", targetNamespace = "http://taxcloud.net")
        java.lang.String state,
        @WebParam(partName = "zip5", name = "zip5", targetNamespace = "http://taxcloud.net")
        java.lang.String zip5,
        @WebParam(partName = "zip4", name = "zip4", targetNamespace = "http://taxcloud.net")
        java.lang.String zip4
    );

    @WebMethod(operationName = "GetTICsByGroup")
    @WebResult(name = "GetTICsRsp", targetNamespace = "http://taxcloud.net", partName = "Body")
    public GetTICsRsp getTICsByGroup(
        @WebParam(partName = "apiLoginID", name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey,
        @WebParam(partName = "ticGroup", name = "ticGroup", targetNamespace = "http://taxcloud.net")
        java.lang.String ticGroup
    );

    @WebMethod(operationName = "Captured")
    @WebResult(name = "CapturedRsp", targetNamespace = "http://taxcloud.net", partName = "Body")
    public CapturedRsp captured(
        @WebParam(partName = "apiLoginID", name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey,
        @WebParam(partName = "orderID", name = "orderID", targetNamespace = "http://taxcloud.net")
        java.lang.String orderID
    );

    @WebMethod(operationName = "DeleteExemptCertificate")
    @WebResult(name = "DeleteCertificateRsp", targetNamespace = "http://taxcloud.net", partName = "Body")
    public DeleteCertificateRsp deleteExemptCertificate(
        @WebParam(partName = "apiLoginID", name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey,
        @WebParam(partName = "certificateID", name = "certificateID", targetNamespace = "http://taxcloud.net")
        java.lang.String certificateID
    );

    @WebMethod(operationName = "GetTICGroups")
    @WebResult(name = "GetTICGroupsRsp", targetNamespace = "http://taxcloud.net", partName = "Body")
    public GetTICGroupsRsp getTICGroups(
        @WebParam(partName = "apiLoginID", name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey
    );

    @WebMethod(operationName = "Ping")
    @WebResult(name = "PingRsp", targetNamespace = "http://taxcloud.net", partName = "Body")
    public PingRsp ping(
        @WebParam(partName = "apiLoginID", name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey
    );

    @WebMethod(operationName = "GetTICs")
    @WebResult(name = "GetTICsRsp", targetNamespace = "http://taxcloud.net", partName = "Body")
    public GetTICsRsp getTICs(
        @WebParam(partName = "apiLoginID", name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey
    );

    @WebMethod(operationName = "Authorized")
    @WebResult(name = "AuthorizedRsp", targetNamespace = "http://taxcloud.net", partName = "Body")
    public AuthorizedRsp authorized(
        @WebParam(partName = "apiLoginID", name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey,
        @WebParam(partName = "customerID", name = "customerID", targetNamespace = "http://taxcloud.net")
        java.lang.String customerID,
        @WebParam(partName = "cartID", name = "cartID", targetNamespace = "http://taxcloud.net")
        java.lang.String cartID,
        @WebParam(partName = "orderID", name = "orderID", targetNamespace = "http://taxcloud.net")
        java.lang.String orderID,
        @WebParam(partName = "dateAuthorized", name = "dateAuthorized", targetNamespace = "http://taxcloud.net")
        java.lang.String dateAuthorized
    );

    @WebMethod(operationName = "GetExemptCertificates")
    @WebResult(name = "GetCertificatesRsp", targetNamespace = "http://taxcloud.net", partName = "Body")
    public GetCertificatesRsp getExemptCertificates(
        @WebParam(partName = "apiLoginID", name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey,
        @WebParam(partName = "customerID", name = "customerID", targetNamespace = "http://taxcloud.net")
        java.lang.String customerID
    );

    @WebMethod(operationName = "AuthorizedWithCapture")
    @WebResult(name = "AuthorizedRsp", targetNamespace = "http://taxcloud.net", partName = "Body")
    public AuthorizedRsp authorizedWithCapture(
        @WebParam(partName = "apiLoginID", name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey,
        @WebParam(partName = "customerID", name = "customerID", targetNamespace = "http://taxcloud.net")
        java.lang.String customerID,
        @WebParam(partName = "cartID", name = "cartID", targetNamespace = "http://taxcloud.net")
        java.lang.String cartID,
        @WebParam(partName = "orderID", name = "orderID", targetNamespace = "http://taxcloud.net")
        java.lang.String orderID,
        @WebParam(partName = "dateAuthorized", name = "dateAuthorized", targetNamespace = "http://taxcloud.net")
        java.lang.String dateAuthorized,
        @WebParam(partName = "dateCaptured", name = "dateCaptured", targetNamespace = "http://taxcloud.net")
        java.lang.String dateCaptured
    );
}
