package net.taxcloud;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2015-01-17T13:56:41.228-05:00
 * Generated source version: 2.6.6
 * 
 */
@WebService(targetNamespace = "http://taxcloud.net", name = "TaxCloudSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface TaxCloudSoap {

    @WebMethod(operationName = "GetTICsByGroup", action = "http://taxcloud.net/GetTICsByGroup")
    @RequestWrapper(localName = "GetTICsByGroup", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.GetTICsByGroup")
    @ResponseWrapper(localName = "GetTICsByGroupResponse", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.GetTICsByGroupResponse")
    @WebResult(name = "GetTICsByGroupResult", targetNamespace = "http://taxcloud.net")
    public net.taxcloud.GetTICsRsp getTICsByGroup(
        @WebParam(name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey,
        @WebParam(name = "ticGroup", targetNamespace = "http://taxcloud.net")
        int ticGroup
    );

    @WebMethod(operationName = "Captured", action = "http://taxcloud.net/Captured")
    @RequestWrapper(localName = "Captured", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.Captured")
    @ResponseWrapper(localName = "CapturedResponse", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.CapturedResponse")
    @WebResult(name = "CapturedResult", targetNamespace = "http://taxcloud.net")
    public net.taxcloud.CapturedRsp captured(
        @WebParam(name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey,
        @WebParam(name = "orderID", targetNamespace = "http://taxcloud.net")
        java.lang.String orderID
    );

    @WebMethod(operationName = "DeleteExemptCertificate", action = "http://taxcloud.net/DeleteExemptCertificate")
    @RequestWrapper(localName = "DeleteExemptCertificate", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.DeleteExemptCertificate")
    @ResponseWrapper(localName = "DeleteExemptCertificateResponse", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.DeleteExemptCertificateResponse")
    @WebResult(name = "DeleteExemptCertificateResult", targetNamespace = "http://taxcloud.net")
    public net.taxcloud.DeleteCertificateRsp deleteExemptCertificate(
        @WebParam(name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey,
        @WebParam(name = "certificateID", targetNamespace = "http://taxcloud.net")
        java.lang.String certificateID
    );

    @WebMethod(operationName = "Lookup", action = "http://taxcloud.net/Lookup")
    @RequestWrapper(localName = "Lookup", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.Lookup")
    @ResponseWrapper(localName = "LookupResponse", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.LookupResponse")
    @WebResult(name = "LookupResult", targetNamespace = "http://taxcloud.net")
    public net.taxcloud.LookupRsp lookup(
        @WebParam(name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey,
        @WebParam(name = "customerID", targetNamespace = "http://taxcloud.net")
        java.lang.String customerID,
        @WebParam(name = "cartID", targetNamespace = "http://taxcloud.net")
        java.lang.String cartID,
        @WebParam(name = "cartItems", targetNamespace = "http://taxcloud.net")
        net.taxcloud.ArrayOfCartItem cartItems,
        @WebParam(name = "origin", targetNamespace = "http://taxcloud.net")
        net.taxcloud.Address origin,
        @WebParam(name = "destination", targetNamespace = "http://taxcloud.net")
        net.taxcloud.Address destination,
        @WebParam(name = "deliveredBySeller", targetNamespace = "http://taxcloud.net")
        boolean deliveredBySeller,
        @WebParam(name = "exemptCert", targetNamespace = "http://taxcloud.net")
        net.taxcloud.ExemptionCertificate exemptCert
    );

    @WebMethod(operationName = "AddTransactions", action = "http://taxcloud.net/AddTransactions")
    @RequestWrapper(localName = "AddTransactions", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.AddTransactions")
    @ResponseWrapper(localName = "AddTransactionsResponse", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.AddTransactionsResponse")
    @WebResult(name = "AddTransactionsResult", targetNamespace = "http://taxcloud.net")
    public net.taxcloud.AddTransactionsRsp addTransactions(
        @WebParam(name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey,
        @WebParam(name = "transactions", targetNamespace = "http://taxcloud.net")
        net.taxcloud.ArrayOfTransaction transactions
    );

    @WebMethod(operationName = "GetTICGroups", action = "http://taxcloud.net/GetTICGroups")
    @RequestWrapper(localName = "GetTICGroups", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.GetTICGroups")
    @ResponseWrapper(localName = "GetTICGroupsResponse", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.GetTICGroupsResponse")
    @WebResult(name = "GetTICGroupsResult", targetNamespace = "http://taxcloud.net")
    public net.taxcloud.GetTICGroupsRsp getTICGroups(
        @WebParam(name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey
    );

    @WebMethod(operationName = "Ping", action = "http://taxcloud.net/Ping")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.PingResponse")
    @WebResult(name = "PingResult", targetNamespace = "http://taxcloud.net")
    public net.taxcloud.PingRsp ping(
        @WebParam(name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey
    );

    @WebMethod(operationName = "AddExemptCertificate", action = "http://taxcloud.net/AddExemptCertificate")
    @RequestWrapper(localName = "AddExemptCertificate", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.AddExemptCertificate")
    @ResponseWrapper(localName = "AddExemptCertificateResponse", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.AddExemptCertificateResponse")
    @WebResult(name = "AddExemptCertificateResult", targetNamespace = "http://taxcloud.net")
    public net.taxcloud.AddCertificateRsp addExemptCertificate(
        @WebParam(name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey,
        @WebParam(name = "customerID", targetNamespace = "http://taxcloud.net")
        java.lang.String customerID,
        @WebParam(name = "exemptCert", targetNamespace = "http://taxcloud.net")
        net.taxcloud.ExemptionCertificate exemptCert
    );

    @WebMethod(operationName = "GetExemptCertificates", action = "http://taxcloud.net/GetExemptCertificates")
    @RequestWrapper(localName = "GetExemptCertificates", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.GetExemptCertificates")
    @ResponseWrapper(localName = "GetExemptCertificatesResponse", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.GetExemptCertificatesResponse")
    @WebResult(name = "GetExemptCertificatesResult", targetNamespace = "http://taxcloud.net")
    public net.taxcloud.GetCertificatesRsp getExemptCertificates(
        @WebParam(name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey,
        @WebParam(name = "customerID", targetNamespace = "http://taxcloud.net")
        java.lang.String customerID
    );

    @WebMethod(operationName = "VerifyAddress", action = "http://taxcloud.net/VerifyAddress")
    @RequestWrapper(localName = "VerifyAddress", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.VerifyAddress")
    @ResponseWrapper(localName = "VerifyAddressResponse", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.VerifyAddressResponse")
    @WebResult(name = "VerifyAddressResult", targetNamespace = "http://taxcloud.net")
    public net.taxcloud.VerifiedAddress verifyAddress(
        @WebParam(name = "uspsUserID", targetNamespace = "http://taxcloud.net")
        java.lang.String uspsUserID,
        @WebParam(name = "address1", targetNamespace = "http://taxcloud.net")
        java.lang.String address1,
        @WebParam(name = "address2", targetNamespace = "http://taxcloud.net")
        java.lang.String address2,
        @WebParam(name = "city", targetNamespace = "http://taxcloud.net")
        java.lang.String city,
        @WebParam(name = "state", targetNamespace = "http://taxcloud.net")
        java.lang.String state,
        @WebParam(name = "zip5", targetNamespace = "http://taxcloud.net")
        java.lang.String zip5,
        @WebParam(name = "zip4", targetNamespace = "http://taxcloud.net")
        java.lang.String zip4
    );

    @WebMethod(operationName = "LookupForDate", action = "http://taxcloud.net/LookupForDate")
    @RequestWrapper(localName = "LookupForDate", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.LookupForDate")
    @ResponseWrapper(localName = "LookupForDateResponse", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.LookupForDateResponse")
    @WebResult(name = "LookupForDateResult", targetNamespace = "http://taxcloud.net")
    public net.taxcloud.LookupRsp lookupForDate(
        @WebParam(name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey,
        @WebParam(name = "customerID", targetNamespace = "http://taxcloud.net")
        java.lang.String customerID,
        @WebParam(name = "cartID", targetNamespace = "http://taxcloud.net")
        java.lang.String cartID,
        @WebParam(name = "cartItems", targetNamespace = "http://taxcloud.net")
        net.taxcloud.ArrayOfCartItem cartItems,
        @WebParam(name = "origin", targetNamespace = "http://taxcloud.net")
        net.taxcloud.Address origin,
        @WebParam(name = "destination", targetNamespace = "http://taxcloud.net")
        net.taxcloud.Address destination,
        @WebParam(name = "deliveredBySeller", targetNamespace = "http://taxcloud.net")
        boolean deliveredBySeller,
        @WebParam(name = "exemptCert", targetNamespace = "http://taxcloud.net")
        net.taxcloud.ExemptionCertificate exemptCert,
        @WebParam(name = "useDate", targetNamespace = "http://taxcloud.net")
        javax.xml.datatype.XMLGregorianCalendar useDate
    );

    @WebMethod(operationName = "GetTICs", action = "http://taxcloud.net/GetTICs")
    @RequestWrapper(localName = "GetTICs", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.GetTICs")
    @ResponseWrapper(localName = "GetTICsResponse", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.GetTICsResponse")
    @WebResult(name = "GetTICsResult", targetNamespace = "http://taxcloud.net")
    public net.taxcloud.GetTICsRsp getTICs(
        @WebParam(name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey
    );

    @WebMethod(operationName = "Authorized", action = "http://taxcloud.net/Authorized")
    @RequestWrapper(localName = "Authorized", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.Authorized")
    @ResponseWrapper(localName = "AuthorizedResponse", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.AuthorizedResponse")
    @WebResult(name = "AuthorizedResult", targetNamespace = "http://taxcloud.net")
    public net.taxcloud.AuthorizedRsp authorized(
        @WebParam(name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey,
        @WebParam(name = "customerID", targetNamespace = "http://taxcloud.net")
        java.lang.String customerID,
        @WebParam(name = "cartID", targetNamespace = "http://taxcloud.net")
        java.lang.String cartID,
        @WebParam(name = "orderID", targetNamespace = "http://taxcloud.net")
        java.lang.String orderID,
        @WebParam(name = "dateAuthorized", targetNamespace = "http://taxcloud.net")
        javax.xml.datatype.XMLGregorianCalendar dateAuthorized
    );

    @WebMethod(operationName = "Returned", action = "http://taxcloud.net/Returned")
    @RequestWrapper(localName = "Returned", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.Returned")
    @ResponseWrapper(localName = "ReturnedResponse", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.ReturnedResponse")
    @WebResult(name = "ReturnedResult", targetNamespace = "http://taxcloud.net")
    public net.taxcloud.ReturnedRsp returned(
        @WebParam(name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey,
        @WebParam(name = "orderID", targetNamespace = "http://taxcloud.net")
        java.lang.String orderID,
        @WebParam(name = "cartItems", targetNamespace = "http://taxcloud.net")
        net.taxcloud.ArrayOfCartItem cartItems,
        @WebParam(name = "returnedDate", targetNamespace = "http://taxcloud.net")
        javax.xml.datatype.XMLGregorianCalendar returnedDate
    );

    @WebMethod(operationName = "AuthorizedWithCapture", action = "http://taxcloud.net/AuthorizedWithCapture")
    @RequestWrapper(localName = "AuthorizedWithCapture", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.AuthorizedWithCapture")
    @ResponseWrapper(localName = "AuthorizedWithCaptureResponse", targetNamespace = "http://taxcloud.net", className = "net.taxcloud.AuthorizedWithCaptureResponse")
    @WebResult(name = "AuthorizedWithCaptureResult", targetNamespace = "http://taxcloud.net")
    public net.taxcloud.AuthorizedRsp authorizedWithCapture(
        @WebParam(name = "apiLoginID", targetNamespace = "http://taxcloud.net")
        java.lang.String apiLoginID,
        @WebParam(name = "apiKey", targetNamespace = "http://taxcloud.net")
        java.lang.String apiKey,
        @WebParam(name = "customerID", targetNamespace = "http://taxcloud.net")
        java.lang.String customerID,
        @WebParam(name = "cartID", targetNamespace = "http://taxcloud.net")
        java.lang.String cartID,
        @WebParam(name = "orderID", targetNamespace = "http://taxcloud.net")
        java.lang.String orderID,
        @WebParam(name = "dateAuthorized", targetNamespace = "http://taxcloud.net")
        javax.xml.datatype.XMLGregorianCalendar dateAuthorized,
        @WebParam(name = "dateCaptured", targetNamespace = "http://taxcloud.net")
        javax.xml.datatype.XMLGregorianCalendar dateCaptured
    );
}
